# Generated by Django 3.1.6 on 2023-09-23 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, unique=True, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('created_on', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Actualité',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, unique=True, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('image', models.ImageField(upload_to='Images/Blog')),
                ('created_on', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
                ('lien', models.TextField(blank=True, verbose_name='lien de la vidéo youtube')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ImagesActualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Images/Blog/ImagesByActu', verbose_name="Images de l'actuaité")),
                ('actualite', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='media.actualite')),
            ],
        ),
    ]
