# Generated by Django 3.1.6 on 2023-09-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230921_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(height_field='160px', upload_to='Images/Blog', width_field='220px'),
        ),
    ]
