# Generated by Django 3.1.6 on 2023-09-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230921_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='lieu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_on',
            field=models.DateField(blank=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
    ]
