# Generated by Django 3.1.6 on 2023-09-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='ImagesActualite',
        ),
    ]
