# Generated by Django 3.1.6 on 2023-09-22 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, unique=True, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('image', models.ImageField(upload_to='Images/Blog')),
                ('created_on', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
            ],
            options={
                'verbose_name': 'Filière',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, unique=True, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images/Blog/ImagesByActu', verbose_name="Images de l'actuaité")),
                ('filiere', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='formation.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, unique=True, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images/Blog/ImagesByActu', verbose_name="Images de l'actuaité")),
                ('formation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='formation.formation')),
            ],
        ),
    ]
