# Generated by Django 3.1.6 on 2023-09-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_auto_20230922_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formation',
            options={'ordering': ['-titre'], 'verbose_name': 'Formation'},
        ),
        migrations.AlterField(
            model_name='formation',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
