# Generated by Django 3.1.6 on 2023-09-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0004_auto_20230922_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='filiere',
            field=models.ForeignKey(default=None, on_delete=models.SET(1), to='formation.filiere'),
        ),
    ]
