# Generated by Django 3.1.6 on 2023-09-22 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0005_auto_20230922_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='filiere',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='formation.filiere'),
        ),
    ]
