# Generated by Django 3.1.6 on 2023-09-22 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0006_auto_20230922_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='filiere',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formation.filiere'),
        ),
    ]
