# Generated by Django 3.1.6 on 2023-09-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0008_auto_20230922_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
