# Generated by Django 3.1.6 on 2023-09-22 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0009_auto_20230922_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/Formations/ImagesFormation', verbose_name="Images de l'actuaité"),
        ),
        migrations.AlterField(
            model_name='option',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/Formations/ImagesFormation', verbose_name='Images de la formation'),
        ),
        migrations.CreateModel(
            name='ModaliteInscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, unique=True, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('filiere', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='formation.filiere')),
            ],
        ),
    ]
