# Generated by Django 3.1.6 on 2023-09-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Nom & Prenom')),
                ('cv', models.FileField(blank=True, null=True, upload_to='Presentation/Admin/CV/')),
                ('image', models.FileField(blank=True, null=True, upload_to='Presentation/Admin/Image/')),
                ('grade', models.CharField(max_length=255, verbose_name='Grade')),
                ('resume', models.TextField(blank=True, max_length=255, null=True, verbose_name='résumé sur le formateur')),
                ('created_on', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Administration',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, unique=True, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Presentation/Cours/Image/')),
                ('fichier', models.ImageField(blank=True, null=True, upload_to='Presentation/Cours/Fichier/')),
                ('created_on', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Les statistiques',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='DirectionGenerale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Nom & Prenom')),
                ('cv', models.FileField(blank=True, null=True, upload_to='Presentation/DG/CV/')),
                ('image', models.FileField(blank=True, null=True, upload_to='Presentation/DG/Image/')),
                ('grade', models.CharField(max_length=255, verbose_name='Grade')),
                ('resume', models.TextField(blank=True, max_length=255, null=True, verbose_name='résumé sur le formateur')),
                ('mot_dg', models.TextField(blank=True, max_length=255, null=True, verbose_name='Le mot du chef')),
                ('created_on', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'DirectionGenerale',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Nom & Prenom')),
                ('cv', models.FileField(blank=True, null=True, upload_to='Presentation/Formateur/CV/')),
                ('image', models.FileField(blank=True, null=True, upload_to='Presentation/Formateur/Image/')),
                ('grade', models.CharField(max_length=255, verbose_name='Grade')),
                ('resume', models.TextField(blank=True, max_length=255, null=True, verbose_name='résumé sur le formateur')),
                ('created_on', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Formateur',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name='Libellé de la classe')),
                ('lien', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lien ou page du partenaire')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'ordering': ['-libelle'],
            },
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, unique=True, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='presentation/Statistique/')),
                ('nombre', models.IntegerField(blank=True, null=True, verbose_name='Date de création')),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Les statistiques',
            },
        ),
    ]
