# Generated by Django 3.1.6 on 2023-09-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistique',
            name='nombre',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chiffre'),
        ),
    ]
