# Generated by Django 3.1.6 on 2023-09-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_auto_20230923_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='libelle',
            field=models.CharField(max_length=255, unique=True, verbose_name='Libellé '),
        ),
    ]
