# Generated by Django 3.1.6 on 2023-09-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0004_partenaire_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['-created_on'], 'verbose_name': 'Les cour'},
        ),
    ]
