# Generated by Django 3.1.6 on 2023-09-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0005_auto_20230923_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Presentation/Admin/Image/'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='Presentation/Cours/Fichier/'),
        ),
        migrations.AlterField(
            model_name='directiongenerale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Presentation/DG/Image/'),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Presentation/Formateur/Image/'),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Presentation/Partenaire/Image/'),
        ),
    ]
